# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.supportedFilesystems = [ "zfs" ];
  boot.kernelParams = [ "net.ifnames=0" ];
  boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;
  boot.initrd.availableKernelModules = [ "uhci_hcd" "ahci" "nvme" "firewire_ohci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.zfs.devNodes = "/dev/disk/by-path";
  boot.zfs.extraPools = [ "bpool" "rpool" ];

  fileSystems."/" =
    { device = "rpool/ROOT/ubuntu_82dr49";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "bpool/BOOT/ubuntu_82dr49";
      fsType = "zfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/8F64-285D";
      fsType = "vfat";
    };

  fileSystems."/home/brett" =
    { device = "rpool/USERDATA/brett_w17ow5";
      fsType = "zfs";
    };

  fileSystems."/srv/data" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  swapDevices =
    [ 
      { device = "/dev/disk/by-uuid/dc9d9ede-6fed-43b0-9bc0-20803105e0ec"; }
    ];

  services.zfs.autoScrub.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
